### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by antoanela** [KevinDockx/JsonPatch.Dynamic#11]
Hi Kevin, I'd like to use this library but it doesn't seem to come with a license. Do you have plans to add one?

Thanks,
Antoanela

**Comment by diaconesq** [comment]
+1 here. I'd like to use this but can't due to legal questions. 
You could just copy the (MIT) `LICENSE` file from the "main" JsonPatch repo.

**Comment by KevinDockx** [comment]
This wasn't intentional - MIT license has been added.
