### ISSUE TITLE
Exception when using JObject.Parse: expects a JsonObjectContract but got a JsonLinqContract

### ISSUE THREAD

**Issue by CedricDumont** [KevinDockx/JsonPatch.Dynamic#5]
The following code
        
           dynamic obj1 = JObject.Parse(@"{'LastName':'Dark', 'FirstName':'Vador'}");

            JsonPatchDocument document = new JsonPatchDocument();
            document.Replace("LastName", "Anakin");

            document.ApplyTo(obj1);

leads to 

                Newtonsoft.Json.Serialization.JsonLinqContract' to type  'Newtonsoft.Json.Serialization.JsonObjectContract'.

Do you have a quick Idea. is it a usage error...

**Comment by daanroeterink** [comment]
You can convert obj1 to Dictionarty<string,object> using jsonconvert.

`JsonConvert.DeserializeObject<Dictionary<string, object>>("{'LastName':'Dark', 'FirstName':'Vador'}");`

 then you won't get this exception.

**Comment by jim-edwards** [comment]
I am running into the same issue, the above work-around only seems to work if the JSON only contains top-level data (IE, no nested elements).  If there is nested elements, they seem to get the JsonLinqContract, even when deserialized as a Dictionary.

It fails in the following JSON:
```
{
   test1:
   {
        test1_1: "1"
   },
   test2:
   {
       test2_1: "2"
   }
}
```
